In [2]:
import torch
import torch.nn as nn

import numpy as np 

In [3]:
class Downsample1d(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.conv = nn.Conv1d(dim, dim, 3, 2, 1)

    def forward(self, x):
        return self.conv(x)


class Upsample1d(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.conv = nn.ConvTranspose1d(dim, dim, 4, 2, 1)

    def forward(self, x):
        return self.conv(x)


#### Downsample Example

In [23]:
# Example input:
a = torch.arange(0, 8, dtype=torch.float32).view(1, -1) # Add batch dimension
print(f"a ({a.shape}):\n{a}")

# Output of Downsample1d:
downsample_1d = Downsample1d(dim=len(a))
downsample_out = downsample_1d(a)

print(f"Downsampled output ({downsample_out.shape}):\n{downsample_out}")

a (torch.Size([1, 8])):
tensor([[0., 1., 2., 3., 4., 5., 6., 7.]])
Downsampled output (torch.Size([1, 4])):
tensor([[-0.6217, -0.6218, -0.1521,  0.3176]], grad_fn=<SqueezeBackward1>)


#### Upsample Example

In [25]:
# Example input:
a = torch.arange(0, 4, dtype=torch.float32).view(1, -1) # Add batch dimension
print(f"a ({a.shape}):\n{a}")

# Output of Downsample1d:
upsample_1d = Upsample1d(dim=len(a))
upsample_out = upsample_1d(a)

print(f"Upsampled output ({upsample_out.shape}):\n{upsample_out}")

a (torch.Size([1, 4])):
tensor([[0., 1., 2., 3.]])
Upsampled output (torch.Size([1, 8])):
tensor([[-0.3003, -0.1834,  0.0246, -0.2721,  0.1318, -0.3607,  0.2389, -0.9170]],
       grad_fn=<SqueezeBackward1>)
